pocketmine.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/pocketmine.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/pocketmine.c -o pocketmine.lo 
kernel/main.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/kernel/filter.c -o kernel/filter.lo 
pocketmine/utils/random.lo: /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/pocketmine/utils/random.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/lib/jenkins/jobs/PocketMine-MP-Zephir/workspace/pocketmine/ext/pocketmine/utils/random.c -o pocketmine/utils/random.lo 
$(phplibdir)/pocketmine.la: ./pocketmine.la
	$(LIBTOOL) --mode=install cp ./pocketmine.la $(phplibdir)

./pocketmine.la: $(shared_objects_pocketmine) $(POCKETMINE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_pocketmine) $(POCKETMINE_SHARED_LIBADD)

